export const arbGames = [
    {
        "id": 1,
        "game": "Ts Galaxy - Steenberg Utd",
        "game_date": "12 August 2020",
        "game_time": "14:30",
        "arb_combination": {
            "naijabet_home": 3.4,
            "bet9ja_draw": 2.96,
            "bet9ja_away": 2.87,
            "roi": "1.96%"
        }, 
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.580Z",
        "book1": "bet9ja",
        "book1_country": "South Africa ",
        "book1_league": "National First Division",
        "book1_game": "Ts Galaxy - Steenberg Utd",
        "book2": "naijabet",
        "book2_country": "South Africa ",
        "book2_league": "National First Division",
        "book2_game": "TS Galaxy vs Steenberg United",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 2,
        "game": "Ts Sporting - Moroka Swallows FC",
        "game_date": "12 August 2020",
        "game_time": "14:30",
        "arb_combination": {
            "bet9ja_home": 4.85,
            "bet9ja_draw": 3.3,
            "naijabet_away": 2.7,
            "roi": "12.04%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.580Z",
        "book1": "bet9ja",
        "book1_country": "South Africa ",
        "book1_league": "National First Division",
        "book1_game": "Ts Sporting - Moroka Swallows FC",
        "book2": "naijabet",
        "book2_country": "South Africa ",
        "book2_league": "National First Division",
        "book2_game": "TS Sporting vs Moroka Swallows FC",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 3,
        "game": "FC Tver - Chita",
        "game_date": "12 August 2020",
        "game_time": "15:00",
        "arb_combination": {
            "bet9ja_home": 2.35,
            "naijabet_draw": 4,
            "naijabet_away": 5.6,
            "roi": "14.59%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.580Z",
        "book1": "bet9ja",
        "book1_country": "Russia ",
        "book1_league": "PFL, Group 2",
        "book1_game": "FC Tver - Chita",
        "book2": "naijabet",
        "book2_country": "Russia ",
        "book2_league": "PFL, Group 2",
        "book2_game": "Volga Tver vs FK Chita",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 4,
        "game": "FC Tver - Chita",
        "game_date": "12 August 2020",
        "game_time": "15:00",
        "arb_combination": {
            "bet9ja_home": 2.35,
            "bet9ja_draw": 3.55,
            "naijabet_away": 5.6,
            "roi": "11.42%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.580Z",
        "book1": "bet9ja",
        "book1_country": "Russia ",
        "book1_league": "PFL, Group 2",
        "book1_game": "FC Tver - Chita",
        "book2": "naijabet",
        "book2_country": "Russia ",
        "book2_league": "PFL, Group 2",
        "book2_game": "Volga Tver vs FK Chita",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 5,
        "game": "Krylia Sovetov Samara - Ska-Khabarovsk",
        "game_date": "12 August 2020",
        "game_time": "16:00",
        "arb_combination": {
            "bet9ja_home": 1.74,
            "naijabet_draw": 3.8,
            "naijabet_away": 6.3,
            "roi": "0.34%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.581Z",
        "book1": "bet9ja",
        "book1_country": "Russia ",
        "book1_league": "Football National League",
        "book1_game": "Krylia Sovetov Samara - Ska-Khabarovsk",
        "book2": "naijabet",
        "book2_country": "Russia ",
        "book2_league": "Football National League",
        "book2_game": "FC Kryliya Sovetov Samara vs FC SKA-Energiya Khabarovsk",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 6,
        "game": "ES Metlaoui - CS Chebba",
        "game_date": "12 August 2020",
        "game_time": "17:00",
        "arb_combination": {
            "bet9ja_home": 2.57,
            "naijabet_draw": 3.14,
            "naijabet_away": 3.76,
            "roi": "2.65%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.581Z",
        "book1": "bet9ja",
        "book1_country": "Tunisia ",
        "book1_league": "Ligue 1",
        "book1_game": "ES Metlaoui - CS Chebba",
        "book2": "naijabet",
        "book2_country": "Tunisia ",
        "book2_league": "Ligue 1",
        "book2_game": "ES Metlaoui vs Chebba",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 7,
        "game": "ES Metlaoui - CS Chebba",
        "game_date": "12 August 2020",
        "game_time": "17:00",
        "arb_combination": {
            "bet9ja_home": 2.57,
            "bet9ja_draw": 2.9,
            "naijabet_away": 3.76,
            "roi": "0.01%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.581Z",
        "book1": "bet9ja",
        "book1_country": "Tunisia ",
        "book1_league": "Ligue 1",
        "book1_game": "ES Metlaoui - CS Chebba",
        "book2": "naijabet",
        "book2_country": "Tunisia ",
        "book2_league": "Ligue 1",
        "book2_game": "ES Metlaoui vs Chebba",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 8,
        "game": "Kaizer Chiefs - Bidvest Wits FC",
        "game_date": "12 August 2020",
        "game_time": "17:00",
        "arb_combination": {
            "naijabet_home": 2.44,
            "bet9ja_draw": 3.15,
            "bet9ja_away": 3.75,
            "roi": "0.60%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.581Z",
        "book1": "bet9ja",
        "book1_country": "South Africa ",
        "book1_league": "Premier League",
        "book1_game": "Kaizer Chiefs - Bidvest Wits FC",
        "book2": "naijabet",
        "book2_country": "South Africa ",
        "book2_league": "Premier League",
        "book2_game": "Kaizer Chiefs FC vs Bidvest Wits FC",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 9,
        "game": "Malmo FF - Orebro",
        "game_date": "12 August 2020",
        "game_time": "18:00",
        "arb_combination": {
            "bet9ja_home": 1.3,
            "naijabet_draw": 6.55,
            "naijabet_away": 12.85,
            "roi": "0.03%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.582Z",
        "book1": "bet9ja",
        "book1_country": "Sweden ",
        "book1_league": "Allsvenskan",
        "book1_game": "Malmo FF - Orebro",
        "book2": "naijabet",
        "book2_country": "Sweden ",
        "book2_league": "Allsvenskan",
        "book2_game": "Malmo FF vs Orebro SK",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 10,
        "game": "Atletico MG - Corinthians",
        "game_date": "12 August 2020",
        "game_time": "23:15",
        "arb_combination": {
            "bet9ja_home": 1.93,
            "naijabet_draw": 3.89,
            "naijabet_away": 4.72,
            "roi": "1.29%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.582Z",
        "book1": "bet9ja",
        "book1_country": "Brazil ",
        "book1_league": "Brasileiro Serie A",
        "book1_game": "Atletico MG - Corinthians",
        "book2": "naijabet",
        "book2_country": "Brazil ",
        "book2_league": "Brasileiro Serie A",
        "book2_game": "Atletico MG vs Corinthians SP",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 11,
        "game": "KS Sleza Wroclaw - Wigry Suwalki",
        "game_date": "13 August 2020",
        "game_time": "15:00",
        "arb_combination": {
            "bet9ja_home": 3.2,
            "bet9ja_draw": 3.5,
            "naijabet_away": 2.5,
            "roi": "0.18%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.583Z",
        "book1": "bet9ja",
        "book1_country": "Poland ",
        "book1_league": "Puchar Polski",
        "book1_game": "KS Sleza Wroclaw - Wigry Suwalki",
        "book2": "naijabet",
        "book2_country": "Poland ",
        "book2_league": "Puchar Polski",
        "book2_game": "Sleza Wroclaw vs Wigry Suwalki",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 12,
        "game": "BSG Chemie Leipzig - BFC Dynamo",
        "game_date": "15 August 2020",
        "game_time": "15:00",
        "arb_combination": {
            "naijabet_home": 2.77,
            "naijabet_draw": 3.72,
            "bet9ja_away": 2.75,
            "roi": "0.65%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.587Z",
        "book1": "bet9ja",
        "book1_country": "Germany ",
        "book1_league": "Regionalliga Northeast",
        "book1_game": "BSG Chemie Leipzig - BFC Dynamo",
        "book2": "naijabet",
        "book2_country": "Germany ",
        "book2_league": "Regionalliga Northeast",
        "book2_game": "Bsg Chemie Leipzig vs BFC Dynamo",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 13,
        "game": "Grodig - Pinzgau Saalfelden",
        "game_date": "18 August 2020",
        "game_time": "18:00",
        "arb_combination": {
            "naijabet_home": 4.6,
            "naijabet_draw": 4.6,
            "bet9ja_away": 1.88,
            "roi": "3.33%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.599Z",
        "book1": "bet9ja",
        "book1_country": "Austria ",
        "book1_league": "Regionalliga Salzburg",
        "book1_game": "Grodig - Pinzgau Saalfelden",
        "book2": "naijabet",
        "book2_country": "Austria ",
        "book2_league": "Regionalliga Salzburg",
        "book2_game": "SV Scholz Grodig vs FC Pinzgau Saalfelden",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 14,
        "game": "Sampaio Correa - Figueirense",
        "game_date": "19 August 2020",
        "game_time": "20:30",
        "arb_combination": {
            "naijabet_home": 3.28,
            "bet9ja_draw": 2.9,
            "bet9ja_away": 2.96,
            "roi": "1.25%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.602Z",
        "book1": "bet9ja",
        "book1_country": "Brazil ",
        "book1_league": "Brasileiro Serie B",
        "book1_game": "Sampaio Correa - Figueirense",
        "book2": "naijabet",
        "book2_country": "Brazil ",
        "book2_league": "Brasileiro Serie B",
        "book2_game": "Sampaio Correa MA vs Figueirense SC",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 15,
        "game": "Sampaio Correa - Figueirense",
        "game_date": "19 August 2020",
        "game_time": "20:30",
        "arb_combination": {
            "naijabet_home": 3.28,
            "naijabet_draw": 3,
            "bet9ja_away": 2.96,
            "roi": "2.40%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.602Z",
        "book1": "bet9ja",
        "book1_country": "Brazil ",
        "book1_league": "Brasileiro Serie B",
        "book1_game": "Sampaio Correa - Figueirense",
        "book2": "naijabet",
        "book2_country": "Brazil ",
        "book2_league": "Brasileiro Serie B",
        "book2_game": "Sampaio Correa MA vs Figueirense SC",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 16,
        "game": "Al-Khor SC - Al Shahaniya",
        "game_date": "20 August 2020",
        "game_time": "17:30",
        "arb_combination": {
            "naijabet_home": 2.16,
            "naijabet_draw": 4,
            "bet9ja_away": 3.5,
            "roi": "0.13%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.603Z",
        "book1": "bet9ja",
        "book1_country": "Qatar ",
        "book1_league": "Stars League",
        "book1_game": "Al-Khor SC - Al Shahaniya",
        "book2": "naijabet",
        "book2_country": "Qatar ",
        "book2_league": "Stars League",
        "book2_game": "Al Khoor vs Al-Shahania SC",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 17,
        "game": "Standard Liege - Genk",
        "game_date": "23 August 2020",
        "game_time": "12:30",
        "arb_combination": {
            "naijabet_home": 2.66,
            "naijabet_draw": 3.37,
            "bet9ja_away": 3.4,
            "roi": "3.32%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.607Z",
        "book1": "bet9ja",
        "book1_country": "Belgium ",
        "book1_league": "First Division A",
        "book1_game": "Standard Liege - Genk",
        "book2": "naijabet",
        "book2_country": "Belgium ",
        "book2_league": "First Division A",
        "book2_game": "Standard Liege vs KRC Genk",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 18,
        "game": "Struga Trim Lum - Borec",
        "game_date": "23 August 2020",
        "game_time": "16:00",
        "arb_combination": {
            "bet9ja_home": 2.1,
            "naijabet_draw": 3.48,
            "naijabet_away": 5.35,
            "roi": "4.95%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.609Z",
        "book1": "bet9ja",
        "book1_country": "Macedonia ",
        "book1_league": "1. MFL",
        "book1_game": "Struga Trim Lum - Borec",
        "book2": "naijabet",
        "book2_country": "Macedonia ",
        "book2_league": "1. MFL",
        "book2_game": "FC Struga Trim Lum vs FK Borec",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 19,
        "game": "Struga Trim Lum - Borec",
        "game_date": "23 August 2020",
        "game_time": "16:00",
        "arb_combination": {
            "bet9ja_home": 2.1,
            "bet9ja_draw": 2.98,
            "naijabet_away": 5.35,
            "roi": "0.13%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.609Z",
        "book1": "bet9ja",
        "book1_country": "Macedonia ",
        "book1_league": "1. MFL",
        "book1_game": "Struga Trim Lum - Borec",
        "book2": "naijabet",
        "book2_country": "Macedonia ",
        "book2_league": "1. MFL",
        "book2_game": "FC Struga Trim Lum vs FK Borec",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 20,
        "game": "OFK Petrovac - Podgorica",
        "game_date": "23 August 2020",
        "game_time": "17:30",
        "arb_combination": {
            "naijabet_home": 3.25,
            "naijabet_draw": 3.1,
            "bet9ja_away": 2.74,
            "roi": "0.48%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.610Z",
        "book1": "bet9ja",
        "book1_country": "Montenegro ",
        "book1_league": "1. CFL",
        "book1_game": "OFK Petrovac - Podgorica",
        "book2": "naijabet",
        "book2_country": "Montenegro ",
        "book2_league": "1. CFL",
        "book2_game": "Ofk Petrovac vs FK Podgorica",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 21,
        "game": "Vasco DA Gama - Gremio",
        "game_date": "23 August 2020",
        "game_time": "20:00",
        "arb_combination": {
            "naijabet_home": 3.36,
            "bet9ja_draw": 3.05,
            "bet9ja_away": 2.83,
            "roi": "2.12%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.610Z",
        "book1": "bet9ja",
        "book1_country": "Brazil ",
        "book1_league": "Brasileiro Serie A",
        "book1_game": "Vasco DA Gama - Gremio",
        "book2": "naijabet",
        "book2_country": "Brazil ",
        "book2_league": "Brasileiro Serie A",
        "book2_game": "Vasco Da Gama RJ vs Gremio RS",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 22,
        "game": "Vasco DA Gama - Gremio",
        "game_date": "23 August 2020",
        "game_time": "20:00",
        "arb_combination": {
            "naijabet_home": 3.36,
            "naijabet_draw": 3.33,
            "bet9ja_away": 2.83,
            "roi": "4.87%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.610Z",
        "book1": "bet9ja",
        "book1_country": "Brazil ",
        "book1_league": "Brasileiro Serie A",
        "book1_game": "Vasco DA Gama - Gremio",
        "book2": "naijabet",
        "book2_country": "Brazil ",
        "book2_league": "Brasileiro Serie A",
        "book2_game": "Vasco Da Gama RJ vs Gremio RS",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 23,
        "game": "Tobol Kostanay - Astana",
        "game_date": "25 August 2020",
        "game_time": "13:00",
        "arb_combination": {
            "naijabet_home": 5.05,
            "bet9ja_draw": 3.05,
            "bet9ja_away": 2.18,
            "roi": "1.54%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.611Z",
        "book1": "bet9ja",
        "book1_country": "Kazakhstan ",
        "book1_league": "Premier League",
        "book1_game": "Tobol Kostanay - Astana",
        "book2": "naijabet",
        "book2_country": "Kazakhstan ",
        "book2_league": "Premier League",
        "book2_game": "Tobol Kostanay vs FC Astana",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 24,
        "game": "Tobol Kostanay - Astana",
        "game_date": "25 August 2020",
        "game_time": "13:00",
        "arb_combination": {
            "naijabet_home": 5.05,
            "naijabet_draw": 3.92,
            "bet9ja_away": 2.18,
            "roi": "8.82%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.611Z",
        "book1": "bet9ja",
        "book1_country": "Kazakhstan ",
        "book1_league": "Premier League",
        "book1_game": "Tobol Kostanay - Astana",
        "book2": "naijabet",
        "book2_country": "Kazakhstan ",
        "book2_league": "Premier League",
        "book2_game": "Tobol Kostanay vs FC Astana",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 25,
        "game": "Sporting Cristal - Alianza Lima",
        "game_date": "25 August 2020",
        "game_time": "20:15",
        "arb_combination": {
            "naijabet_home": 2.23,
            "naijabet_draw": 3.68,
            "bet9ja_away": 3.7,
            "roi": "0.96%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.612Z",
        "book1": "bet9ja",
        "book1_country": "Peru ",
        "book1_league": "Primera Division, Apertura",
        "book1_game": "Sporting Cristal - Alianza Lima",
        "book2": "naijabet",
        "book2_country": "Peru ",
        "book2_league": "Primera Division, Apertura",
        "book2_game": "Sporting Cristal vs Alianza Lima",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 26,
        "game": "FH Hafnarfjordur - Dac 1904 Dunajska Streda",
        "game_date": "27 August 2020",
        "game_time": "18:15",
        "arb_combination": {
            "bet9ja_home": 4.25,
            "bet9ja_draw": 3.8,
            "naijabet_away": 2.02,
            "roi": "0.65%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.614Z",
        "book1": "bet9ja",
        "book1_country": "International Clubs ",
        "book1_league": "UEFA Europa League, Qualification",
        "book1_game": "FH Hafnarfjordur - Dac 1904 Dunajska Streda",
        "book2": "naijabet",
        "book2_country": "International Clubs ",
        "book2_league": "UEFA Europa League, Qualification",
        "book2_game": "FH Hafnarfjordur vs Dac 1904 Dunajska Streda",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 27,
        "game": "WSC Hertha - Wolfsberger AC (A)",
        "game_date": "01 September 2020",
        "game_time": "18:00",
        "arb_combination": {
            "bet9ja_home": 1.34,
            "naijabet_draw": 8.46,
            "naijabet_away": 14.1,
            "roi": "6.46%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.617Z",
        "book1": "bet9ja",
        "book1_country": "Austria ",
        "book1_league": "Regionalliga Centre",
        "book1_game": "WSC Hertha - Wolfsberger AC (A)",
        "book2": "naijabet",
        "book2_country": "Austria ",
        "book2_league": "Regionalliga Centre",
        "book2_game": "WSC Hertha Wels vs Wolfsberger AC II",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 28,
        "game": "Stellenbosch - Amazulu Durban",
        "game_date": "02 September 2020",
        "game_time": "17:00",
        "arb_combination": {
            "naijabet_home": 2.74,
            "bet9ja_draw": 3.2,
            "bet9ja_away": 3.6,
            "roi": "4.48%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.618Z",
        "book1": "bet9ja",
        "book1_country": "South Africa ",
        "book1_league": "Premier League",
        "book1_game": "Stellenbosch - Amazulu Durban",
        "book2": "naijabet",
        "book2_country": "South Africa ",
        "book2_league": "Premier League",
        "book2_game": "Stellenbosch FC vs Amazulu FC",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    },
    {
        "id": 29,
        "game": "Stellenbosch - Amazulu Durban",
        "game_date": "02 September 2020",
        "game_time": "17:00",
        "arb_combination": {
            "naijabet_home": 2.74,
            "naijabet_draw": 3.22,
            "bet9ja_away": 3.6,
            "roi": "4.67%"
        },
        "showfulldata": false,
        "sport": "Soccer",
        "market":"1X2",
        "arb_received": "2020-09-13T11:28:17.618Z",
        "book1": "bet9ja",
        "book1_country": "South Africa ",
        "book1_league": "Premier League",
        "book1_game": "Stellenbosch - Amazulu Durban",
        "book2": "naijabet",
        "book2_country": "South Africa ",
        "book2_league": "Premier League",
        "book2_game": "Stellenbosch FC vs Amazulu FC",
        "book3": null,
        "book3_country": null,
        "book3_league": null,
        "book3_game": null
    }
]